version: "3.3"
services:
  mysql:
    ports:
      -  "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes: 
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: test
    image: "mysql:5.7.35"
    container_name: "mysql"
  idea_bucket:
    ports:
      -  "1200:1200"
    restart: always
    image: "shane/idea_bucket:latest"
    depends_on:
      - "mysql"
