---
version: "3"

networks:
  services:
    driver: overlay
  db:
    driver: overlay

services:
  idea-bucket-client:
    image: idea-bucket-client
    environment:
      - "NEXT_PUBLIC_MODE=prod"
    networks:
      - services
    ports:
      - 80:3000
  idea-bucket-server:
    image: idea-bucket-server
    ports:
      - 8080:8080
    networks:
      - services
      - db
    environment:
      - "MONGO_DB_HOST=mongo"
      - "EMAIL_SENDER=me@shanel.ee"
      - "SPRING_MAIL_HOST=smtp.zoho.eu"
      - "SPRING_MAIL_USERNAME=me@shanel.ee"
      - "SPRING_MAIL_PASSWORD=${MAIL_PASS}"
      - "SPRING_MAIL_PORT=465"
      - "EMAIL_SUPPORT_DESTINATION=me@shanel.ee"
  mongo:
    image: mongo:5.0.6
    ports:
      - 27017:27017
    networks:
      - db
